create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id text primary key default 'main',
  top_bar_text text not null default 'আজকের Flash Offer চলছে - প্রতি প্যাকেট মাত্র ৫৯ টাকা',
  highlight_title text not null default 'চলছে 59-টাকার অফিশিয়াল মিস্ট্রি বক্স অফার.!',
  highlight_subtitle text not null default 'মাত্র ৫৯ টাকায় সেরা সারপ্রাইজটি কি আপনার হবে?',
  hero_title text not null default 'মাত্র ৫৯ টাকায় Daraz Mystery Box Surprise',
  hero_description text not null default 'সারপ্রাইজ প্যাকেট অর্ডার করুন, ঘরে বসে Cash on Delivery-তে রিসিভ করুন। প্রতিটি প্যাকেটে কী থাকবে সেটাই আসল মিস্ট্রি।',
  telegram_link text not null default 'https://t.me/DarzMysteryBox24',
  price_per_packet integer not null default 59 check (price_per_packet >= 0),
  delivery_charge integer not null default 99 check (delivery_charge >= 0),
  order_block_days integer not null default 15 check (order_block_days >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.package_options (
  id bigint generated by default as identity primary key,
  packet_count integer not null unique check (packet_count > 0),
  label text not null,
  badge text not null default '',
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  is_available boolean not null default true,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  address text not null,
  note text,
  package_count integer not null,
  subtotal integer not null,
  delivery_charge integer not null,
  total integer not null,
  device_hash text,
  ip_hash text,
  courier_check_status text not null default 'pending' check (courier_check_status in ('pending', 'checking', 'success', 'error')),
  courier_checked_at timestamptz,
  courier_check_result jsonb,
  courier_check_error text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'delivered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_device_hash_created_at_idx
on public.orders (device_hash, created_at desc)
where device_hash is not null;

create index if not exists orders_ip_hash_created_at_idx
on public.orders (ip_hash, created_at desc)
where ip_hash is not null;

create index if not exists orders_courier_check_status_idx
on public.orders (courier_check_status, created_at desc);

create table if not exists public.pixel_settings (
  id text primary key default 'main',
  meta_pixel_enabled boolean not null default false,
  meta_pixel_id text not null default '',
  meta_capi_enabled boolean not null default false,
  meta_access_token text not null default '',
  meta_test_event_code text not null default '',
  gtm_enabled boolean not null default false,
  gtm_container_id text not null default '',
  tiktok_pixel_enabled boolean not null default false,
  tiktok_pixel_id text not null default '',
  tiktok_events_enabled boolean not null default false,
  tiktok_access_token text not null default '',
  tiktok_test_event_code text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.courier_settings (
  id text primary key default 'main',
  api_key text not null default '',
  updated_at timestamptz not null default now()
);

create or replace function public.decrement_package_stock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.package_options
  set
    stock_quantity = greatest(stock_quantity - 1, 0),
    is_available = case when greatest(stock_quantity - 1, 0) = 0 then false else is_available end,
    badge = case when greatest(stock_quantity - 1, 0) = 0 then 'স্টক আউট' else badge end,
    updated_at = now()
  where packet_count = new.package_count;

  return new;
end;
$$;

drop trigger if exists decrement_package_stock_after_order on public.orders;
create trigger decrement_package_stock_after_order
after insert on public.orders
for each row execute function public.decrement_package_stock();

create or replace function public.claim_courier_check(target_order_id uuid)
returns table(id uuid, phone text)
language sql
security definer
set search_path = public
as $$
  update public.orders
  set
    courier_check_status = 'checking',
    courier_check_error = null,
    updated_at = now()
  where public.orders.id = target_order_id
    and public.orders.courier_checked_at is null
    and (
      public.orders.courier_check_status <> 'checking'
      or public.orders.updated_at < now() - interval '30 seconds'
    )
  returning public.orders.id, public.orders.phone;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.site_settings (id)
values ('main')
on conflict (id) do nothing;

insert into public.pixel_settings (id)
values ('main')
on conflict (id) do nothing;

insert into public.courier_settings (id)
values ('main')
on conflict (id) do nothing;

insert into public.package_options (packet_count, label, badge, stock_quantity, is_available, display_order)
values
  (6, '৬ প্যাকেট', 'Popular', 100, true, 1),
  (7, '৭ প্যাকেট', 'Available', 100, true, 2),
  (10, '১০ প্যাকেট', 'Best Value', 100, true, 3)
on conflict (packet_count) do nothing;

alter table public.site_settings enable row level security;
alter table public.package_options enable row level security;
alter table public.orders enable row level security;
alter table public.profiles enable row level security;
alter table public.pixel_settings enable row level security;
alter table public.courier_settings enable row level security;

grant select on public.site_settings to anon, authenticated;
grant select on public.package_options to anon, authenticated;
revoke insert on public.orders from anon, authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, update, delete on public.site_settings to authenticated;
grant select, insert, update, delete on public.package_options to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.pixel_settings to authenticated;
grant select, insert, update, delete on public.courier_settings to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings for select
using (true);

drop policy if exists "Admins can update site settings" on public.site_settings;
create policy "Admins can update site settings"
on public.site_settings for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read package options" on public.package_options;
create policy "Public can read package options"
on public.package_options for select
using (true);

drop policy if exists "Admins can manage package options" on public.package_options;
create policy "Admins can manage package options"
on public.package_options for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Anyone can create orders" on public.orders;

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders"
on public.orders for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage pixel settings" on public.pixel_settings;
create policy "Admins can manage pixel settings"
on public.pixel_settings for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage courier settings" on public.courier_settings;
create policy "Admins can manage courier settings"
on public.courier_settings for all
using (public.is_admin())
with check (public.is_admin());

-- After creating your admin user in Supabase Auth, run this with that user's email:
-- insert into public.profiles (id, email, is_admin)
-- select id, email, true from auth.users where email = 'admin@example.com'
-- on conflict (id) do update set is_admin = true, email = excluded.email;
